/**
 * Isolated mock data for offline development and UI testing.
 * Only activated when VITE_USE_MOCK_DATA=true.
 * Production mode defaults to false (real AWS APIs).
 */

export const mockTenants = [
  {
    tenant_id: "tenant-acme-corp",
    status: "READY",
    host_id: "host-i-0a812b4e9f301d2a1",
    private_ip: "10.0.1.42",
    mysql_port: 3307,
    database_name: "tenant_acme_corp_db",
    mysql_username: "user_acme_corp",
    credentials_secret_arn: "arn:aws:secretsmanager:ap-south-1:123456789012:secret:multi-tenant-mysql/tenants/dev/tenant-acme-corp-A9xL",
    environment: "dev",
    created_at: new Date(Date.now() - 3600 * 1000 * 24 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000 * 24 * 2).toISOString(),
  },
  {
    tenant_id: "tenant-globex-systems",
    status: "READY",
    host_id: "host-i-0a812b4e9f301d2a1",
    private_ip: "10.0.1.42",
    mysql_port: 3307,
    database_name: "tenant_globex_systems_db",
    mysql_username: "user_globex_systems",
    credentials_secret_arn: "arn:aws:secretsmanager:ap-south-1:123456789012:secret:multi-tenant-mysql/tenants/dev/tenant-globex-systems-K3mP",
    environment: "dev",
    created_at: new Date(Date.now() - 3600 * 1000 * 24 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000 * 24 * 1).toISOString(),
  },
  {
    tenant_id: "tenant-initech-ltd",
    status: "READY",
    host_id: "host-i-0a812b4e9f301d2a1",
    private_ip: "10.0.1.42",
    mysql_port: 3307,
    database_name: "tenant_initech_ltd_db",
    mysql_username: "user_initech_ltd",
    credentials_secret_arn: "arn:aws:secretsmanager:ap-south-1:123456789012:secret:multi-tenant-mysql/tenants/dev/tenant-initech-ltd-R7vB",
    environment: "dev",
    created_at: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000 * 11).toISOString(),
  },
  {
    tenant_id: "tenant-stark-ind",
    status: "BOOTSTRAPPING",
    host_id: "host-i-0c749e1a8b204f5e3",
    private_ip: "10.0.1.88",
    mysql_port: 3307,
    database_name: "tenant_stark_ind_db",
    mysql_username: "user_stark_ind",
    credentials_secret_arn: null,
    environment: "dev",
    created_at: new Date(Date.now() - 60000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 60000 * 2).toISOString(),
  },
  {
    tenant_id: "tenant-wayne-ent",
    status: "PENDING",
    host_id: null,
    private_ip: null,
    mysql_port: 3307,
    database_name: null,
    mysql_username: null,
    credentials_secret_arn: null,
    environment: "dev",
    created_at: new Date(Date.now() - 60000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 60000 * 1).toISOString(),
  },
  {
    tenant_id: "tenant-umbrella-corp",
    status: "FAILED",
    host_id: "host-i-0a812b4e9f301d2a1",
    private_ip: "10.0.1.42",
    mysql_port: 3307,
    database_name: null,
    mysql_username: null,
    credentials_secret_arn: null,
    environment: "dev",
    created_at: new Date(Date.now() - 3600 * 1000 * 30).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000 * 29).toISOString(),
  },
];

export const mockJobs = [
  {
    job_id: "7f4c3981-9b12-4c65-8ea1-2a839f904011",
    tenant_id: "tenant-wayne-ent",
    status: "PENDING",
    stage: "STEP_FUNCTIONS_STARTED",
    environment: "dev",
    state_machine_execution_arn: "arn:aws:states:ap-south-1:123456789012:execution:multi-tenant-mysql-host-provisioning-dev:tenant-9b124c",
    created_at: new Date(Date.now() - 60000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 60000 * 1).toISOString(),
  },
  {
    job_id: "5c2e1742-1a48-4390-bf32-91f82e113a02",
    tenant_id: "tenant-stark-ind",
    status: "BOOTSTRAPPING",
    stage: "BOOTSTRAP_HOST",
    environment: "dev",
    target_host: {
      host_id: "host-i-0c749e1a8b204f5e3",
      private_ip: "10.0.1.88",
    },
    created_at: new Date(Date.now() - 60000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 60000 * 2).toISOString(),
  },
  {
    job_id: "1a8b9204-7c33-4de1-90fa-4e7829103822",
    tenant_id: "tenant-initech-ltd",
    status: "READY",
    stage: "READY",
    environment: "dev",
    created_at: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000 * 12 + 45000).toISOString(),
  },
  {
    job_id: "3e9d8210-4f51-419b-a012-984712048512",
    tenant_id: "tenant-umbrella-corp",
    status: "FAILED",
    stage: "READINESS_CHECK",
    environment: "dev",
    error_code: "ReadinessTimeout",
    error: "Timed out waiting for MySQL to respond on TCP port 3307 after 15 retries.",
    created_at: new Date(Date.now() - 3600 * 1000 * 30).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000 * 29).toISOString(),
  },
];

export const mockHosts = [
  {
    host_id: "host-i-0a812b4e9f301d2a1",
    status: "READY",
    private_ip: "10.0.1.42",
    mysql_port: 3307,
    tenant_count: 3,
    capacity: 5,
    available_capacity: 2,
    subnet_id: "subnet-07b489a291f0a1c9e",
    environment: "dev",
    created_at: new Date(Date.now() - 3600 * 1000 * 24 * 7).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
  },
  {
    host_id: "host-i-0c749e1a8b204f5e3",
    status: "BOOTSTRAPPING",
    private_ip: "10.0.1.88",
    mysql_port: 3307,
    tenant_count: 1,
    capacity: 5,
    available_capacity: 4,
    subnet_id: "subnet-07b489a291f0a1c9e",
    environment: "dev",
    created_at: new Date(Date.now() - 60000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 60000 * 2).toISOString(),
  },
];

export const mockBackups = [
  {
    backup_id: "b94f18a2-2d10-49c8-82f1-098432174201",
    tenant_id: "tenant-acme-corp",
    s3_bucket: "multi-tenant-mysql-backups-dev",
    s3_key: "tenants/tenant-acme-corp/b94f18a2-2d10-49c8-82f1-098432174201.sql.gz",
    size_bytes: 421890,
    created_at: new Date(Date.now() - 3600 * 1000 * 24 * 1).toISOString(),
    status: "COMPLETED",
  },
  {
    backup_id: "d83a9104-5e21-4871-91a3-832104928172",
    tenant_id: "tenant-globex-systems",
    s3_bucket: "multi-tenant-mysql-backups-dev",
    s3_key: "tenants/tenant-globex-systems/d83a9104-5e21-4871-91a3-832104928172.sql.gz",
    size_bytes: 184520,
    created_at: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
    status: "COMPLETED",
  },
];

export const mockHealth = {
  status: "Healthy",
  environment: "dev",
  region: "ap-south-1",
  timestamp: new Date().toISOString(),
  services: {
    api_gateway: {
      name: "Amazon API Gateway",
      status: "Healthy",
      latency_ms: 24,
    },
    lambda: {
      name: "AWS Lambda",
      status: "Healthy",
      environment: "dev",
    },
    dynamodb: {
      name: "Amazon DynamoDB",
      status: "Healthy",
      latency_ms: 18,
      details: "Tables: multi-tenant-mysql-tenants-dev, multi-tenant-mysql-jobs-dev, multi-tenant-mysql-hosts-dev",
    },
    step_functions: {
      name: "AWS Step Functions",
      status: "Healthy",
      arn: "arn:aws:states:ap-south-1:123456789012:stateMachine:multi-tenant-mysql-host-provisioning-dev",
    },
    ec2_hosts: {
      name: "EC2 MySQL Hosts",
      status: "Healthy",
      total_hosts: 2,
      ready_hosts: 1,
    },
    s3: {
      name: "Amazon S3",
      status: "Healthy",
      bucket: "multi-tenant-mysql-backups-dev",
    },
    secrets_manager: {
      name: "AWS Secrets Manager",
      status: "Healthy",
      note: "Credential isolation active",
    },
  },
};
