import json
import os
import shlex
from datetime import datetime, timezone

import boto3
from botocore.exceptions import ClientError


TENANTS_TABLE_NAME = os.environ["TENANTS_TABLE_NAME"]
HOSTS_TABLE_NAME = os.environ["HOSTS_TABLE_NAME"]
BACKUP_BUCKET_NAME = os.environ["BACKUP_BUCKET_NAME"]
ENVIRONMENT = os.environ.get("ENVIRONMENT", "dev")
MYSQL_PORT = int(os.environ.get("MYSQL_PORT", "3307"))


dynamodb = boto3.resource("dynamodb")

tenants_table = dynamodb.Table(
    TENANTS_TABLE_NAME
)

hosts_table = dynamodb.Table(
    HOSTS_TABLE_NAME
)

ssm = boto3.client("ssm")
s3 = boto3.client("s3")


def response(status_code, body):
    return {
        "statusCode": status_code,
        "body": body
    }


def utc_now():
    return datetime.now(
        timezone.utc
    ).isoformat()


def get_required_backup_id(event):
    backup_id = event.get("backup_id")

    if not backup_id:
        return None, response(
            400,
            {
                "message": "backup_id is required"
            }
        )

    backup_id = str(backup_id).strip()

    if not backup_id:
        return None, response(
            400,
            {
                "message": "backup_id is required"
            }
        )

    # Backup IDs are UUIDs generated by the backup service.
    # Reject path-like values so a caller cannot alter the
    # tenant prefix of the S3 object.
    if (
        "/" in backup_id
        or "\\" in backup_id
        or ".." in backup_id
    ):
        return None, response(
            400,
            {
                "message": "Invalid backup_id"
            }
        )

    return backup_id, None


def handler(event, context):

    tenant_id = event.get("tenant_id")

    if not tenant_id:
        return response(
            400,
            {
                "message": "tenant_id is required"
            }
        )

    backup_id, validation_response = (
        get_required_backup_id(event)
    )

    if validation_response:
        return validation_response

    try:

        # ==================================================
        # 1. GET TENANT
        # ==================================================

        tenant_result = tenants_table.get_item(
            Key={
                "tenant_id": tenant_id
            }
        )

        tenant = tenant_result.get(
            "Item"
        )

        if not tenant:
            return response(
                404,
                {
                    "message": "Tenant not found",
                    "tenant_id": tenant_id
                }
            )

        if tenant.get("status") != "READY":
            return response(
                409,
                {
                    "message": "Tenant is not READY",
                    "tenant_id": tenant_id,
                    "status": tenant.get("status")
                }
            )

        host_id = tenant.get("host_id")
        database_name = tenant.get(
            "database_name"
        )

        if not host_id:
            raise RuntimeError(
                "Tenant host_id is missing"
            )

        if not database_name:
            raise RuntimeError(
                "Tenant database_name is missing"
            )

        # ==================================================
        # 2. GET HOST
        # ==================================================

        host_result = hosts_table.get_item(
            Key={
                "host_id": host_id
            }
        )

        host = host_result.get(
            "Item"
        )

        if not host:
            return response(
                404,
                {
                    "message": "Host not found",
                    "host_id": host_id
                }
            )

        if host.get("status") != "READY":
            return response(
                409,
                {
                    "message": "Host is not READY",
                    "host_id": host_id,
                    "status": host.get("status")
                }
            )

        host_secret_arn = host.get(
            "secret_arn"
        )

        if not host_secret_arn:
            raise RuntimeError(
                "Host secret ARN is missing"
            )

        # ==================================================
        # 3. BUILD AND VERIFY S3 BACKUP OBJECT
        # ==================================================

        s3_key = (
            f"tenants/"
            f"{tenant_id}/"
            f"{backup_id}.sql.gz"
        )

        try:
            object_metadata = s3.head_object(
                Bucket=BACKUP_BUCKET_NAME,
                Key=s3_key
            )
        except ClientError as error:

            error_code = (
                error.response
                .get("Error", {})
                .get("Code", "Unknown")
            )

            if error_code in {
                "404",
                "NoSuchKey",
                "NotFound"
            }:
                return response(
                    404,
                    {
                        "message": "Backup not found",
                        "tenant_id": tenant_id,
                        "backup_id": backup_id,
                        "s3_key": s3_key
                    }
                )

            raise

        content_length = object_metadata.get(
            "ContentLength"
        )

        if content_length is not None and content_length <= 0:
            return response(
                409,
                {
                    "message": "Backup object is empty",
                    "tenant_id": tenant_id,
                    "backup_id": backup_id,
                    "s3_key": s3_key
                }
            )

        # ==================================================
        # 4. QUOTE VALUES FOR THE REMOTE SHELL
        # ==================================================

        secret_arn_q = shlex.quote(
            host_secret_arn
        )

        bucket_q = shlex.quote(
            BACKUP_BUCKET_NAME
        )

        key_q = shlex.quote(
            s3_key
        )

        database_q = shlex.quote(
            database_name
        )

        mysql_port_q = shlex.quote(
            str(MYSQL_PORT)
        )

        # ==================================================
        # 5. REMOTE RESTORE SCRIPT
        # ==================================================
        #
        # The EC2 instance:
        #   - retrieves its host admin secret
        #   - downloads the tenant backup from S3
        #   - decompresses it
        #   - restores the SQL into MySQL
        #
        # The backup key is restricted to this tenant's
        # own S3 prefix.
        #
        # ==================================================

        commands = [

            "set -e",

            "TMP_DIR=$(mktemp -d)",

            'trap \'rm -rf "$TMP_DIR"\' EXIT',

            # ------------------------------
            # Build Python restore script
            # ------------------------------

            'cat > "$TMP_DIR/run_restore.py" <<\'PY\'',

            "import json",
            "import os",
            "import subprocess",
            "import boto3",

            "",

            'region = os.environ.get("AWS_REGION", "ap-south-1")',

            'secret_arn = os.environ["HOST_SECRET_ARN"]',
            'bucket = os.environ["BACKUP_BUCKET"]',
            'key = os.environ["BACKUP_KEY"]',
            'database = os.environ["DATABASE_NAME"]',
            'mysql_port = os.environ["MYSQL_PORT"]',

            "",

            'sm = boto3.client('
            '"secretsmanager", '
            'region_name=region'
            ')',

            's3 = boto3.client('
            '"s3", '
            'region_name=region'
            ')',

            "",

            'secret_response = sm.get_secret_value(',
            '    SecretId=secret_arn',
            ')',

            'secret = json.loads(',
            '    secret_response["SecretString"]',
            ')',

            'username = (',
            '    secret.get("admin_username")',
            '    or secret.get("mysql_admin_username")',
            '    or secret.get("username")',
            ')',

            'password = (',
            '    secret.get("admin_password")',
            '    or secret.get("mysql_admin_password")',
            '    or secret.get("password")',
            ')',

            'if not username:',
            '    raise RuntimeError("Host admin username missing")',

            'if not password:',
            '    raise RuntimeError("Host admin password missing")',

            "",

            'config_path = "/tmp/my.cnf"',

            'with open(config_path, "w") as f:',
            '    f.write("[client]\\n")',
            '    f.write("host=127.0.0.1\\n")',
            '    f.write(f"port={mysql_port}\\n")',
            '    f.write(f"user={username}\\n")',
            '    f.write(f"password={password}\\n")',

            'os.chmod(config_path, 0o600)',

            "",

            'gzip_path = "/tmp/tenant_restore.sql.gz"',

            's3.download_file(',
            '    bucket,',
            '    key,',
            '    gzip_path',
            ')',

            "",

            "# Verify the archive before touching MySQL.",
            'subprocess.run(',
            '    ["gzip", "-t", gzip_path],',
            '    check=True',
            ')',

            "",

            "# The backup was produced with mysqldump --databases,",
            "# so the dump contains the database-selection statements.",
            'restore_command = [',
            '    "mysql",',
            '    f"--defaults-extra-file={config_path}"',
            ']',

            'with open(gzip_path, "rb") as compressed_input:',
            '    gzip_process = subprocess.Popen(',
            '        ["gzip", "-dc", gzip_path],',
            '        stdout=subprocess.PIPE,',
            '        stderr=subprocess.PIPE',
            '    )',

            '    mysql_process = subprocess.run(',
            '        restore_command,',
            '        stdin=gzip_process.stdout,',
            '        stdout=subprocess.PIPE,',
            '        stderr=subprocess.PIPE,',
            '        check=False',
            '    )',

            '    if gzip_process.stdout is not None:',
            '        gzip_process.stdout.close()',

            '    gzip_return_code = gzip_process.wait()',

            '    if gzip_return_code != 0:',
            '        raise RuntimeError(',
            '            "gzip decompression failed: "',
            '            + gzip_process.stderr.read().decode(',
            '                "utf-8",',
            '                errors="replace"',
            '            )',
            '        )',

            '    if mysql_process.returncode != 0:',
            '        raise RuntimeError(',
            '            "MySQL restore failed: "',
            '            + mysql_process.stderr.decode(',
            '                "utf-8",',
            '                errors="replace"',
            '            )',
            '        )',

            "",

            "# Verify that the target database is reachable.",
            'verification = subprocess.run(',
            '    [',
            '        "mysql",',
            '        f"--defaults-extra-file={config_path}",',
            '        "-Nse",',
            '        f"USE `{database.replace("`", "``")}`; SELECT 1;"',
            '    ],',
            '    stdout=subprocess.PIPE,',
            '    stderr=subprocess.PIPE,',
            '    text=True',
            ')',

            'if verification.returncode != 0:',
            '    raise RuntimeError(',
            '        "Database verification failed: "',
            '        + verification.stderr',
            '    )',

            'print("RESTORE_COMPLETED")',
            'print(f"RESTORE_DATABASE={database}")',
            'print(f"S3_BUCKET={bucket}")',
            'print(f"S3_KEY={key}")',

            "PY",

            # ------------------------------
            # Export values for the script
            # ------------------------------

            f"export HOST_SECRET_ARN={secret_arn_q}",

            f"export BACKUP_BUCKET={bucket_q}",

            f"export BACKUP_KEY={key_q}",

            f"export DATABASE_NAME={database_q}",

            f"export MYSQL_PORT={mysql_port_q}",

            # ------------------------------
            # Execute restore
            # ------------------------------

            'python3 "$TMP_DIR/run_restore.py"'
        ]

        # ==================================================
        # 6. SEND SSM COMMAND
        # ==================================================

        command_result = ssm.send_command(
            InstanceIds=[
                host_id
            ],

            DocumentName="AWS-RunShellScript",

            Comment=(
                f"MySQL restore "
                f"for tenant {tenant_id} "
                f"from backup {backup_id}"
            ),

            Parameters={
                "commands": commands
            },

            TimeoutSeconds=1800
        )

        print(
            "SSM RESTORE COMMAND RESPONSE:",
            json.dumps(
                command_result,
                default=str
            )
        )

        command_id = (
            command_result["Command"]["CommandId"]
        )

        print(
            "SSM RESTORE COMMAND ID:",
            command_id
        )

        # ==================================================
        # 7. RETURN IMMEDIATELY
        # ==================================================

        return response(
            202,
            {
                "message":
                    "Tenant restore started",

                "tenant_id":
                    tenant_id,

                "host_id":
                    host_id,

                "database_name":
                    database_name,

                "backup_id":
                    backup_id,

                "command_id":
                    command_id,

                "s3_bucket":
                    BACKUP_BUCKET_NAME,

                "s3_key":
                    s3_key,

                "backup_size_bytes":
                    content_length,

                "status":
                    "IN_PROGRESS",

                "created_at":
                    utc_now()
            }
        )

    except ClientError as error:

        error_code = (
            error.response
            .get("Error", {})
            .get("Code", "Unknown")
        )

        print(
            "AWS restore error:",
            error_code,
            str(error)
        )

        return response(
            500,
            {
                "message":
                    "Failed to start tenant restore",

                "tenant_id":
                    tenant_id,

                "backup_id":
                    backup_id,

                "error_code":
                    error_code
            }
        )

    except Exception as error:

        print(
            "Tenant restore failed:",
            type(error).__name__,
            str(error)
        )

        return response(
            500,
            {
                "message":
                    "Tenant restore failed",

                "tenant_id":
                    tenant_id,

                "backup_id":
                    backup_id,

                "error":
                    str(error)
            }
        )
